from update_repo import update_file

# 🔴 STEP 1: paste code generated by Antigravity here
new_code = """ 
import React from "react";

function App() {
  return (
    <div>
      <h1>Welcome to Namibia Travel Share 🌍</h1>
      <p>Explore and share your journeys!</p>
    </div>
  );
}

export default App;
"""

# 🔴 STEP 2: specify which file to update in your repo
file_path = "src/App.js"

# 🔴 STEP 3: commit message
commit_message = "AI update: improved homepage UI"

# 🔴 STEP 4: push update
update_file(file_path, new_code, commit_message)

print("✅ Code updated successfully!")
